// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'appointment_list.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

AppointmentList _$AppointmentListFromJson(Map<String, dynamic> json) =>
    AppointmentList(
      queueId: (json['queue_id'] as num?)?.toInt(),
      queueState: json['queue_state'] as String?,
      appointmentId: (json['appointment_id'] as num?)?.toInt(),
      patientId: (json['patient_id'] as num?)?.toInt(),
      doctorId: (json['doctor_id'] as num?)?.toInt(),
      familyId: (json['family_id'] as num?)?.toInt(),
      doctorName: json['doctor_name'] as String?,
      specialization: json['specialization'] as String?,
      experience: (json['experience'] as num?)?.toInt(),
      clinicId: json['clinic_id'] as String?,
      gender: json['gender'] as String?,
      appointmentDate: json['appointment_date'] as String?,
      dob: json['DOB'] as String?,
      queueNumber: (json['queue_number'] as num?)?.toInt(),
      bookingType: (json['booking_type'] as num?)?.toInt(),
      startTime: json['start_time'] as String?,
      endTime: json['end_time'] as String?,
      status: json['status'] as String?,
      userType: (json['user_type'] as num?)?.toInt(),
      bookingFor: json['booking_for'] as String?,
      clinicAddress: json['clinic_address'] as String?,
      clinicName: json['clinic_name'] as String?,
      latitude: (json['latitude'] as num?)?.toDouble(),
      longitude: (json['longitude'] as num?)?.toDouble(),
      clinicContact: json['clinic_contact'] as String?,
      queueStatus: (json['queue_status'] as num?)?.toInt(),
      myQueueNumber: (json['my_queue_number'] as num?)?.toInt(),
      patientsAhead: (json['patients_ahead'] as num?)?.toInt(),
      estimatedArrivalTime: json['estimated_arrival_time'] as String?,
      queueStarted: json['queue_started'] as bool?,
      isMyTurn: json['is_my_turn'] as bool?,
      cancelledBy: json['cancelled_by'] as String?,
      totalQueue: (json['total_queue'] as num?)?.toInt(),
      currentServing: (json['current_serving'] as num?)?.toInt(),
      symptoms: json['symptoms'] as String?,
      isReviewed: json['is_reviewed'] as bool?,
    )..patientName = json['patient_name'] as String?;

Map<String, dynamic> _$AppointmentListToJson(AppointmentList instance) =>
    <String, dynamic>{
      'appointment_id': instance.appointmentId,
      'patient_id': instance.patientId,
      'queue_id': instance.queueId,
      'doctor_id': instance.doctorId,
      'family_id': instance.familyId,
      'doctor_name': instance.doctorName,
      'specialization': instance.specialization,
      'experience': instance.experience,
      'clinic_id': instance.clinicId,
      'clinic_name': instance.clinicName,
      'clinic_address': instance.clinicAddress,
      'clinic_contact': instance.clinicContact,
      'latitude': instance.latitude,
      'longitude': instance.longitude,
      'gender': instance.gender,
      'appointment_date': instance.appointmentDate,
      'DOB': instance.dob,
      'queue_number': instance.queueNumber,
      'booking_type': instance.bookingType,
      'start_time': instance.startTime,
      'end_time': instance.endTime,
      'status': instance.status,
      'booking_for': instance.bookingFor,
      'user_type': instance.userType,
      'patient_name': instance.patientName,
      'queue_status': instance.queueStatus,
      'my_queue_number': instance.myQueueNumber,
      'patients_ahead': instance.patientsAhead,
      'estimated_arrival_time': instance.estimatedArrivalTime,
      'queue_state': instance.queueState,
      'queue_started': instance.queueStarted,
      'is_my_turn': instance.isMyTurn,
      'cancelled_by': instance.cancelledBy,
      'total_queue': instance.totalQueue,
      'current_serving': instance.currentServing,
      'symptoms': instance.symptoms,
      'is_reviewed': instance.isReviewed,
    };
