// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'doctor_details.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

DoctorDetails _$DoctorDetailsFromJson(Map<String, dynamic> json) =>
    DoctorDetails(
      doctorId: (json['doctor_id'] as num?)?.toInt(),
      name: json['name'] as String?,
      email: json['email'] as String?,
      mobile: json['mobile'] as String?,
      qualification: json['qualification'] as String?,
      licenseNo: json['license_no'] as String?,
      experience: (json['experience'] as num?)?.toInt(),
      specialization: json['specialization'] as String?,
      image: json['image'] as String?,
      roleId: (json['role_id'] as num?)?.toInt(),
      Token: json['token'] as String?,
      clinicId: json['clinic_id'] as String?,
      clinicName: json['clinic_name'] as String?,
      clinicAddress: json['clinic_address'] as String?,
      latitude: _doubleFromJson(json['latitude']),
      longitude: _doubleFromJson(json['longitude']),
      consultationFee: _doubleFromJson(json['consultation_fee']),
      websiteName: json['website_name'] as String?,
      clinicEmail: json['clinic_email'] as String?,
      clinicContact: json['clinic_contact'] as String?,
      imageUrl: json['image_url'] as String?,
      genderId: (json['gender_id'] as num?)?.toInt(),
      leadTime: _intFromJson(json['q_start_before']),
      qStartSection: _intFromJson(json['q_start_section']),
      queueLength: _intFromJson(json['queue_length']),
      isQueueAvailable: _intFromJson(json['is_queue_available']),
      isSlotAvailable: _intFromJson(json['is_slot_available']),
      isBookingStarted: _intFromJson(json['is_booking_started']),
      currentQueueLength: _intFromJson(json['current_queue_length']),
      maxQueueLength: _intFromJson(json['max_queue_length']),
      isQueueFull: _intFromJson(json['is_queue_full']),
      bookingStartTime: json['booking_start_time'] as String?,
      isRecentlyVisited: json['is_recently_visited'] as String?,
    );

Map<String, dynamic> _$DoctorDetailsToJson(DoctorDetails instance) =>
    <String, dynamic>{
      'doctor_id': instance.doctorId,
      'name': instance.name,
      'email': instance.email,
      'mobile': instance.mobile,
      'qualification': instance.qualification,
      'license_no': instance.licenseNo,
      'experience': instance.experience,
      'specialization': instance.specialization,
      'image': instance.image,
      'role_id': instance.roleId,
      'token': instance.Token,
      'clinic_id': instance.clinicId,
      'clinic_name': instance.clinicName,
      'clinic_address': instance.clinicAddress,
      'latitude': instance.latitude,
      'longitude': instance.longitude,
      'consultation_fee': instance.consultationFee,
      'website_name': instance.websiteName,
      'clinic_email': instance.clinicEmail,
      'clinic_contact': instance.clinicContact,
      'image_url': instance.imageUrl,
      'gender_id': instance.genderId,
      'q_start_before': instance.leadTime,
      'q_start_section': instance.qStartSection,
      'queue_length': instance.queueLength,
      'is_queue_available': instance.isQueueAvailable,
      'is_slot_available': instance.isSlotAvailable,
      'is_booking_started': instance.isBookingStarted,
      'current_queue_length': instance.currentQueueLength,
      'max_queue_length': instance.maxQueueLength,
      'is_queue_full': instance.isQueueFull,
      'booking_start_time': instance.bookingStartTime,
      'is_recently_visited': instance.isRecentlyVisited,
    };
